# Generated by Django 2.2.19 on 2021-03-21 21:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog_home', '0002_auto_20210321_1027'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='tittle',
            new_name='title',
        ),
    ]
